# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.CharField(max_length=200)),
                ('calories_count', models.CharField(blank=True, default=None, max_length=200)),
                ('ingredient_date', models.DateField(default='2010-01-01', verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ManyToManyField(to='ratatouille.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guide', models.CharField(blank=True, max_length=200)),
                ('suffix', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guide_filter', models.CharField(blank=True, max_length=5000)),
                ('ingredient_filter', models.CharField(blank=True, default=None, max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='website_link',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ratatouille.WebSite'),
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratatouille.Recipe'),
        ),
    ]
